import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import ProjectCard from "./ProjectCards";
import Particle from "../Particle";
import parkinsons from "../../Assets/Projects/parkinsons.png";
import money from "../../Assets/Projects/money.png";
import rajasthan from "../../Assets/Projects/rajasthan.png";
import email from "../../Assets/Projects/email.png";
import ai from "../../Assets/Projects/ai.png";
import attendence from "../../Assets/Projects/attendence.png";

function Projects() {
  return (
    <Container fluid className="project-section">
      <Particle />
      <Container>
        <h1 className="project-heading">
          My Recent <strong className="purple">Works </strong>
        </h1>
        <p style={{ color: "white" }}>
          Here are a few projects I've worked on recently.
        </p>
        <Row style={{ justifyContent: "center", paddingBottom: "10px" }}>
          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={parkinsons}
              isBlog={false}
              title="Parkinson's Detector"
              description="This project involves a machine learning model that predicts whether a person has Parkinson's disease (PD) based on their voice samples. The model works by analyzing features extracted from audio recordings (WAV or MP3 format) and classifying them as either healthy or Parkinson's based on voice characteristics."
              ghLink="https://github.com/Garvanand/Parkinsons_detection-LSTM-"
              demoLink="https://parkinsonsdetection.streamlit.app/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={attendence}
              isBlog={false}
              title="Attendence Tracker"
              description="An Attendance Tracker using Facial Recognition automates attendance marking by identifying individuals through facial features. It uses OpenCV (cv2) for real-time face detection and recognition, comparing detected faces with a pre-registered database. Recognized individuals are logged into a database with details like name, date, and time. The system features a tkinter GUI for user interaction, allowing attendance tracking, record viewing, and adding new faces. "
              ghLink="https://github.com/Garvanand/VIT_Attendance_Tracker"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={rajasthan}
              isBlog={false}
              title="Rajasthan Club website"
              description="The Rajasthan Club Website, built with React and Tailwind CSS, showcases Rajasthan's culture, heritage, and events. This responsive, user-friendly platform offers an immersive experience, connecting enthusiasts to traditions, tourist spots, and community activities for our college club, blending creativity and functionality seamlessly."
              ghLink="https://github.com/Garvanand/Rajasthan_Club"
              demoLink="https://rajasthan-club.vercel.app/"              
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={email}
              isBlog={false}
              title="Spam Email Detector"
              description="The Email Spam Detection App, built with Streamlit, Python, and Scikit-learn, allows users to classify emails as spam or not spam. This interactive, user-friendly tool leverages machine learning for accurate predictions, providing a seamless experience for email filtering. A practical project showcasing AI and web development integration."
              ghLink="https://github.com/Garvanand/streamlit-emailspam-"
              demoLink="https://nex7lrbmbqnsspsw5urtcs.streamlit.app/"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={ai}
              isBlog={false}
              title="Ai Generated text detector"
              description="he AI-Generated Text Detector is a machine-learning model designed to detect and classify AI-generated text. It utilizes natural language processing (NLP) techniques and deep learning algorithms to identify text generated by AI systems, such as language models like GPT (Generative Pre-trained Transformer) models."
              ghLink="https://github.com/Garvanand/AI-generated-text-detector"
            />
          </Col>

          <Col md={4} className="project-card">
            <ProjectCard
              imgPath={money}
              isBlog={false}
              title="Financial Advisory Bot"
              description="we're redefining financial advisory services with cutting-edge generative AI technology. Our mission is to democratize personalized financial advice, provide real-time insights, ensure transparency, and scale efficiently to meet diverse user needs."
              ghLink="https://github.com/Dev-Team-VIT/Financial-Advisory-Bot"
              demoLink="https://money-mantra-pi.vercel.app/"
            />
          </Col>
        </Row>
      </Container>
    </Container>
  );
}

export default Projects;
